# Generated by Django 2.0.3 on 2022-10-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructionprojects',
            old_name='project_client',
            new_name='projectclient',
        ),
    ]
