# Generated by Django 2.0.3 on 2022-10-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construct', '0004_auto_20221011_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
